// Code generated by mockery v2.47.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// GetBook is an autogenerated mock type for the GetBook type
type GetBook struct {
	mock.Mock
}

// GetAllBooks provides a mock function with given fields: w, r
func (_m *GetBook) GetAllBooks(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetBook provides a mock function with given fields: w, r
func (_m *GetBook) GetBook(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewGetBook creates a new instance of GetBook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetBook(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetBook {
	mock := &GetBook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
